#MCTrade Config File
mysql:
  hostname: localhost
  port: 3306
  username: root
  password:
  database: Minecraft
Web:
  MctradeDirectory: http://websitename.com/mctrade/
  Access:
    Moderator:
      - SomeModsNameHere
    Admin:
      - SomeAdminsNameHere
TradeOptions:
  UpdateChecker: true
  Tax: 2.00
