#MCTrade Config File
mysql:
  #hostname: is the url in which is used to connect to your database. Simply remove localhost and put the url here which should be provided by your host!
  hostname: localhost
  #Port: port number may not be provided but 3306 is the defaul port used for MySQL databases so this should be fine as is.
  port: 3306
  #username:  is the username used for the MySQL database
  username: root
  #password: is the password used for the MySQL database
  password: 123
  #database: is the name of the database
  database: Minecraft
#Web related settings!
Web:
  #Web access level controls!
  Access:
    # Grant a user access to moderator featurss on the website. This only affects website permissions, NOT in game permissions! To give a user mod permissions in game use permission: mctrade.mod
    Moderator:
    #  - SomeModsNameHere
    #  - AnotherModExample
    # Gives a user access to admin features on the website, not in game! To give admin permissions in game use the permission: mctrade.admin
    Admin:
    #  - SomeAdminsNameHere
    #  - AnotherAdminExample
#General trade options
TradeOptions:
  #If true, you will be notified in the console if a new version of MCTrade is released.
  VersionNotifications: true
  #This is the amount of tax a user is charged when they create a trade. Please make sure to include at least 2 decimal places as seen below. The tax works by simply multiplying the price the user is selling the item for by the tax and then charging the user that result. 0.02 is a 2% tax charged. If you want no tax just make it 0.00
  Tax: 0.02
  #Should MCTrade check users IP's when making a trade. WARNING: Enabling this may prevent users from the same house from being able to accept other members trades from the same house!
  CheckTradeIP: false
  
