name: MCTrade
main: me.fogest.mctrade.MCTrade
<<<<<<< HEAD
version: 1.03
=======
version: 1.04
>>>>>>> v1.1
description: Makes trading a tad bit easier
website: http://fogest.com
author: Fogest

depend: [Vault]

commands:
  mctrade:
    description: Used to start a trade
    aliases: [mct]
  trade:
    description: Used to perform administrative commands

permissions:
  mctrade.*:
    description: Gives access to all MCTrade Commands
    children:
      mctrade.mctrade : true
      mctrade.trade: true
  mctrade.mctrade:
    description: Basic command used to see /mctrade usage info
    default: true
  mctrade.trade:
    description: Allows you to perform administrative commands
    default: op

