name: MCTrade
main: me.fogest.mctrade.MCTrade
version: 1.05
description: Makes trading a tad bit easier
website: http://fogest.com
author: Fogest

depend: [Vault]

commands:
  mctrade:
    description: Used to start a trade
    aliases: [mct]

permissions:
  mctrade.*:
    description: Gives access to all MCTrade Commands
    children:
      mctrade.mctrade : true
      mctrade.trade: true
  mctrade.mctrade:
    description: Basic command used to see /mctrade usage info
    default: true

