name: MCTrade
main: me.fogest.mctrade.MCTrade
description: Makes trading a tad bit easier
version: 0.1
website: http://fogest.net16.net
author: Fogest

depend: [Vault]

commands:
  mctrade:
    description: Used to start a trade
    aliases: [mct]
  trade:
    description: Used to perform administrative commands

permissions:
  mctrade.*:
    description: Gives access to all MCTrade Commands
    children:
      mctrade.mctrade.*: true
      mctrade.trade: true
      mctrade.mctrade.trade: true
      mctrade.mctrade.verify: true
      mctrade.mctrade.accept: true
  mctrade.mctrade.*:
    description: Allows you access to all the commands that use /mctrade
    default: true
    children:
      mctrade.mctrade.trade: true
      mctrade.mctrade.verify: true
      mctrade.mctrade.accept: true
  mctrade.mctrade.trade:
    description: Allows you to create a trade
    defaut: true
  mctrade.mctrade.verify:
    description: Essential command if the user also can use trade
    default: true
  mctrade.mctrade.accept:
    description: Allows users to accept trades
    default: true
  mctrade.trade:
    description: Allows you to perform administrative commands
    default: op