name: MCTrade
main: me.fogest.mctrade.MCTrade
description: Makes trading a tad bit easier
version: 0.1
website: http://fogest.net16.net
author: Fogest


commands:
  mctrade:
    description: Used to start a trade
    aliases: [mct]
    usage: /mctrade