name: MCTrade
main: me.fogest.mctrade.MCTrade
version: 1.10
description: Makes trading a tad bit easier
website: http://fogest.com
author: Fogest

depend: [Vault]

commands:
  mctrade:
    description: Used to start a trade
    aliases: [mct]

permissions:
  mctrade.*:
    description: Gives access to all MCTrade Commands
    children:
      mctrade.mctrade : true
      mctrade.trade : true
      mctrade.create : true
      mctrade.accept : true
    default: op
  mctrade.mctrade:
    description: Basic command used to see /mctrade usage info
    default: true
  mctrade.help:
    description: Allows user to use /mct help to list commands and functions of those commands!
  mctrade.trade:
    description: Allows user to use /mct (num 1-9) to create a trade!
    default: true
  mctrade.create:
    description: Allows users to use /mct create to create a MCTrade account.
    default: true
  mctrade.accept:
    description: Allows users to use /mct accept to accept a trade.
    default: true
