name: MCTrade
main: me.fogest.mctrade.MCTrade
description: Makes trading a tad bit easier
version: 0.1
website: http://fogest.net16.net
author: Fogest

commands:
  mctrade:
    description: Used to start a trade
    aliases: [mct]
  trade:
    description: Used to perform administrative commands

permissions:
  mctrade.*:
    description: Gives access to all MCTrade Commands
    children:
      mctrade.mctrade: true
      mctrade.trade: true
  mctrade.mctrade:
    description: Allows you to create a trade
    default: true
  mctrade.trade:
    description: Allows you to perform administrative commands
    default: op